version: '2.1'

services:
  mysql:
    image: 'docker.io/bitnami/mysql:latest'
    ports:
      - '8091:3306'
    volumes:
      - /c/volumes/mysql:/bitnami/mysql/data
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - MYSQL_ROOT_PASSWORD=Psmcg4t1PElyyKs3VHVF]
      - MYSQL_DATABASE=oauth
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

volumes:
  mysql_data:
    driver: local